connector.name=iceberg
iceberg.catalog.type=glue

hive.metastore.glue.region=us-east-1

fs.native-s3.enabled=true
s3.region=us-east-1

iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.add-files-procedure.enabled=true
